kind: pipeline
type: ssh
name: default

trigger:
  branch:
    - drone
  event:
    - push

server:
  host: 172.31.39.73
  user: ubuntu
  ssh_key:
    from_secret: ssh_key

steps:
  - name: docker
    commands:
      - docker build -t dcr.teletraan.io/public/toy:latest .
